Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,3 +1,165 @@
-z="
-";iEz='hen';fCz='g se';WCz='$HOM';yFz=' 1';xCz='aw/r';pDz='ps:/';EGz='ated';Lz='\033';pFz=' "Pl';nBz='"Dep';MGz='rks.';aFz='u"';Ez='GREE';fBz='ired';RCz='ect"';dz=' -e ';CCz='"Dow';ZDz='_sh(';GEz='.sh ';hz='{NC}';yEz='ATH=';wFz='n."';qFz='ease';xEz='rt P';JBz='inst';jz='}';iCz='fi';vDz='nstt';TGz='ull;';lCz='-O "';xz='${NC';hGz='all.';Qz='33[0';sEz='"$HO';JDz='ownl';rDz='hub.';sFz=' ins';SDz='r "F';LIz='ce ~';KBz='all_';aEz='[ ":';Rz=';34m';DBz='"${Y';PBz='log ';MBz='nden';bEz='$PAT';YCz='n/.s';Cz='3[0;';qCz='ub.c';cEz='H:" ';MCz='[ -f';LFz='H"';HHz='h';NDz='sful';pGz='on-m';lGz='erco';TBz='ckag';HDz='"sel';PFz='nu_c';DDz='t"; ';vGz='fs/h';rGz='3/Te';xGz='/Tes';YDz='_gtm';mCz='t" "';tGz='-bet';bBz='"Ins';rEz=' >> ';GHz='ll.s';sDz='com/';sHz='nd';RHz='clea';AEz='refs';TDz='aile';uGz='a/re';EIz=' Or ';cDz='ng w';PCz='bin/';REz='"Set';sCz='agi1';lHz='"Sta';GCz='ect.';dGz='main';Nz='3m'\''';Tz='CYAN';fHz='r   ';eBz='requ';Pz='='\''\0';aCz='t"';hDz='; th';rz='$1"';CHz='u_in';ez='"${B';UIz=' is ';WIz='"Ple';LGz='d wo';Yz='o Co';uDz='17/d';uEz='bash';xDz='ent/';fDz='.gtm';QGz='nu &';aDz=' gtm';gEz='"* ]';DEz='ain/';UBz='e li';tFz=' scr';ZHz='    ';ZFz='n/gt';EDz='then';NIz='shrc';KFz='y in';YFz='enu"';EBz='ELLO';ZCz='elec';MDz='cces';NHz='lled';oHz='lati';bCz='"Rem';gHz=' ║"';VHz=' "╔═';DHz='./me';Zz='lor';hEz=']; t';bFz='d"';mBz='ess ';tBz='essf';pz='!]${';OCz='OME/';dIz='c"';gBz=' pac';CFz='PATH';aBz='y';ECz='ding';FBz='W}[!';QFz='omma';wGz='eads';ZIz=' sou';TIz='ll; ';mFz='ot f';cIz='ashr';wBz='load';KCz='t...';XDz='rn 1';lEz=' PAT';bIz='~/.b';xHz='PLET';QBz='"Upd';PHz='nu"';gz='[*]$';WEz='ory.';wDz='-cli';UEz='~/bi';SGz='ev/n';ADz='head';hFz=' '\''EO';yDz='raw/';WFz='d...';qz='NC} ';lFz='sh n';Mz='[1;3';PEz='rect';cz='echo';fGz='-O m';XBz='pkg ';wHz=' COM';dHz='Inst';UHz='YAN}';jGz='raw.';HIz='f av';ACz='sh()';eCz='stin';NEz='p_bi';XEz='mkdi';eEz='":$H';DIz='ype:';dBz='ing ';THz='"${C';AHz='l.sh';RGz='> /d';VDz=' dow';DGz=' cre';IHz='rm m';Gz='033[';tHz='INST';nz='"${R';Hz='0;32';kHz='C}"';JIz='ble)';Bz=''\''\03';BCz=' {';IIz='aila';KHz='"Mai';RFz='nd()';OFz='tmme';jCz='if w';HGz='"Che';XHz='═╗"';BDz='s/ma';vCz='clie';gCz='lect';xBz='_sel';yHz='E   ';HFz='in i';aGz='t fo';JHz='sh';fz='LUE}';eDz='.."';oDz='"htt';KIz='sour';BFz='in:$';wEz='expo';cHz='enu ';FHz='nsta';Iz='m'\''';FIz='use:';pEz=':$PA';JFz='read';GBz=']${N';yz='} $1';mDz='m"';KDz='oade';UGz='"men';CDz='in/s';RDz='else';Kz='OW='\''';SFz='"Cre';MHz='nu i';pCz='gith';TFz='mmen';bHz='TM M';BIz='open';tCz='7/dn';bGz='und.';VFz='mman';JGz='g if';AIz=' To ';dEz='!= *';jEz=' '\''ex';kDz='tm"';VBz='st..';MFz='crea';wCz='nt/r';XFz='gtmm';vz='REEN';LHz='n me';OIz='"Tes';hCz='.sh"';YGz='le"';NCz=' "$H';Uz=';36m';FFz=' to ';sz='succ';vEz='rc"';wz='}[✓]';XIz='ase ';iBz='s...';ZEz='bin"';GGz='_com';fFz='menu';SBz='g pa';kGz='ubus';nHz='g in';gGz='enu_';rFz=' run';BBz='warn';LCz='if [';lz='r() ';YEz='r -p';RBz='atin';ZBz='te -';jFz=' "Er';YHz=' "║ ';mGz='nten';nEz='HOME';YIz='run:';JCz=' wge';uFz='ipt ';cFz='cat ';UFz='u co';WGz=' ava';kFz='ror:';NFz='te_g';ZGz='d no';oGz='m/Jh';HBz='C} $';Wz='[0m'\''';uBz='ully';QDz='rn 0';pBz='ncie';oEz='/bin';JEz='ssfu';Jz='YELL';lBz=' -y';HCz='sh u';nGz='t.co';kCz='get ';eHz='alle';VGz='d is';YBz='upda';VIz='y!"';kBz='wget';ICz='sing';uCz='stt-';SHz='r';OHz=' mai';BEz='/hea';GIz='u (i';AGz='EOF';dDz='get.';OEz='n_di';EEz='gtm"';rHz='_sh';mEz='H="$';CIz='u, t';Xz=' # N';PIz='v gt';qBz='s in';DCz='nloa';vBz='down';CEz='ds/m';kz='erro';gFz='" <<';tz='ess(';rBz='stal';iHz='═╝"';XCz='E/bi';WBz='."';CGz='mand';VEz='n di';IGz='ckin';SIz='v/nu';bDz=' usi';cGz=' Ins';EFz='ed ~';uHz='ALLA';RIz=' /de';nCz='http';Oz='BLUE';UCz='n';QEz='ory(';qEz='TH"'\''';GDz='d +x';IFz='s al';jHz='"${N';yBz='ect_';QIz='u &>';sGz='rmux';FDz='chmo';hBz='kage';vFz='agai';Vz='NC='\''';oFz='!"';mz='{';BGz=' com';oCz='s://';IDz='sh d';WHz='════';Fz='N='\''\';LBz='depe';eGz='u...';qHz='ory';mHz='rtin';OGz='nd -';KEz='lly"';cBz='tall';XGz='ilab';uz='"${G';cCz='oved';Dz='31m'\''';vHz='TION';sBz='led ';Sz=''\''';nFz='ound';WDz='d se';ABz='"';yCz='efs/';oz='ED}[';QHz='_ins';iz=' $1"';AFz='ME/b';LEz='d gt';yGz='t/in';hHz=' "╚═';Az='RED=';SEz='ting';QCz='.sel';DFz='"Add';VCz='rm "';rCz='om/m';MIz='/.ba';oBz='ende';gDz='" ]]';EHz='nu_i';xFz='exit';CBz='ing(';KGz=' men';dFz='> "$';ODz='ly"';MEz='setu';HEz='ed s';pHz='on..';bz=') {';qDz='/git';NBz='cies';iDz='en';jDz='n/.g';UDz='d to';fEz='bin:';IBz='1"';tDz='magi';FEz='"gtm';iGz='sh "';jBz='all ';SCz=' ]];';PDz='retu';PGz='v me';tEz='ME/.';aIz='rce ';BHz='"; t';NGz='if c';LDz='d su';nDz='tm" ';FGz='fix_';GFz='"~/b';eFz='/gtm';aHz='   G';IEz='ucce';az='log(';TCz=' the';FCz=' sel';kEz='port';qGz='ark2';iFz='F'\''';lDz='g gt';TEz=' up ';OBz='() {';dCz=' exi';
-eval "$Az$Bz$Cz$Dz$z$Ez$Fz$Gz$Hz$Iz$z$Jz$Kz$Lz$Mz$Nz$z$Oz$Pz$Qz$Rz$Sz$z$Tz$Pz$Qz$Uz$Sz$z$Vz$Lz$Wz$Xz$Yz$Zz$z$az$bz$z$cz$dz$ez$fz$gz$hz$iz$z$jz$z$kz$lz$mz$z$cz$dz$nz$oz$pz$qz$rz$z$jz$z$sz$tz$bz$z$cz$dz$uz$vz$wz$xz$yz$ABz$z$jz$z$BBz$CBz$bz$z$cz$dz$DBz$EBz$FBz$GBz$HBz$IBz$z$jz$z$JBz$KBz$LBz$MBz$NBz$OBz$z$PBz$QBz$RBz$SBz$TBz$UBz$VBz$WBz$z$XBz$YBz$ZBz$aBz$z$PBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$ABz$z$XBz$JBz$jBz$kBz$lBz$z$sz$mBz$nBz$oBz$pBz$qBz$rBz$sBz$sz$tBz$uBz$ABz$z$jz$z$vBz$wBz$xBz$yBz$ACz$BCz$z$PBz$CCz$DCz$ECz$FCz$GCz$HCz$ICz$JCz$KCz$ABz$z$LCz$MCz$NCz$OCz$PCz$QCz$RCz$SCz$TCz$UCz$z$VCz$WCz$XCz$YCz$ZCz$aCz$z$PBz$bCz$cCz$dCz$eCz$fCz$gCz$hCz$z$iCz$z$jCz$kCz$lCz$WCz$XCz$YCz$ZCz$mCz$nCz$oCz$pCz$qCz$rCz$sCz$tCz$uCz$vCz$wCz$xCz$yCz$ADz$BDz$CDz$ZCz$DDz$EDz$z$FDz$GDz$NCz$OCz$PCz$QCz$RCz$z$sz$mBz$HDz$GCz$IDz$JDz$KDz$LDz$MDz$NDz$ODz$z$PDz$QDz$z$RDz$z$kz$SDz$TDz$UDz$VDz$DCz$WDz$gCz$ABz$z$PDz$XDz$z$iCz$z$jz$z$vBz$wBz$YDz$ZDz$bz$z$PBz$CCz$DCz$ECz$aDz$bDz$cDz$dDz$eDz$z$LCz$MCz$NCz$OCz$PCz$fDz$gDz$hDz$iDz$z$VCz$WCz$XCz$jDz$kDz$z$PBz$bCz$cCz$dCz$eCz$lDz$mDz$z$iCz$z$jCz$kCz$lCz$WCz$XCz$jDz$nDz$oDz$pDz$qDz$rDz$sDz$tDz$uDz$vDz$wDz$xDz$yDz$AEz$BEz$CEz$DEz$EEz$hDz$iDz$z$FDz$GDz$NCz$OCz$PCz$fDz$ABz$z$sz$mBz$FEz$GEz$vBz$wBz$HEz$IEz$JEz$KEz$z$PDz$QDz$z$RDz$z$kz$SDz$TDz$UDz$VDz$DCz$LEz$mDz$z$PDz$XDz$z$iCz$z$jz$z$MEz$NEz$OEz$PEz$QEz$bz$z$PBz$REz$SEz$TEz$UEz$VEz$PEz$WEz$eDz$z$XEz$YEz$NCz$OCz$ZEz$z$LCz$aEz$bEz$cEz$dEz$eEz$OCz$fEz$gEz$hEz$iEz$z$cz$jEz$kEz$lEz$mEz$nEz$oEz$pEz$qEz$rEz$sEz$tEz$uEz$vEz$z$wEz$xEz$yEz$sEz$AFz$BFz$CFz$ABz$z$sz$mBz$DFz$EFz$oEz$FFz$CFz$ABz$z$RDz$z$PBz$GFz$HFz$IFz$JFz$KFz$lEz$LFz$z$iCz$z$jz$z$MFz$NFz$OFz$PFz$QFz$RFz$BCz$z$PBz$SFz$RBz$lDz$TFz$UFz$VFz$WFz$ABz$z$LCz$MCz$NCz$OCz$PCz$XFz$YFz$SCz$TCz$UCz$z$VCz$WCz$XCz$ZFz$TFz$aFz$z$PBz$bCz$cCz$dCz$eCz$lDz$TFz$UFz$VFz$bFz$z$iCz$z$cFz$dFz$nEz$oEz$eFz$fFz$gFz$hFz$iFz$z$LCz$MCz$NCz$OCz$PCz$QCz$RCz$SCz$TCz$UCz$z$uEz$NCz$OCz$PCz$QCz$RCz$z$RDz$z$cz$jFz$kFz$FCz$GCz$lFz$mFz$nFz$oFz$z$cz$pFz$qFz$rFz$TCz$sFz$cBz$tFz$uFz$vFz$wFz$z$xFz$yFz$z$iCz$z$AGz$z$FDz$GDz$NCz$OCz$PCz$XFz$YFz$z$sz$mBz$FEz$fFz$BGz$CGz$DGz$EGz$ABz$z$jz$z$FGz$fFz$GGz$CGz$OBz$z$PBz$HGz$IGz$JGz$KGz$UFz$VFz$LGz$MGz$eDz$z$NGz$QFz$OGz$PGz$QGz$RGz$SGz$TGz$TCz$UCz$z$sz$mBz$UGz$UFz$VFz$VGz$WGz$XGz$YGz$z$PDz$QDz$z$RDz$z$BBz$dBz$UGz$UFz$VFz$ZGz$aGz$bGz$cGz$cBz$dBz$dGz$KGz$eGz$ABz$z$jCz$kCz$fGz$gGz$JBz$hGz$iGz$nCz$oCz$jGz$pCz$kGz$lGz$mGz$nGz$oGz$pGz$qGz$rGz$sGz$tGz$uGz$vGz$wGz$xGz$yGz$rBz$AHz$BHz$iEz$z$FDz$GDz$KGz$CHz$rBz$AHz$z$DHz$EHz$FHz$GHz$HHz$z$IHz$gGz$JBz$hGz$JHz$z$sz$mBz$KHz$LHz$MHz$FHz$NHz$ABz$z$PDz$QDz$z$RDz$z$kz$SDz$TDz$UDz$sFz$cBz$OHz$LHz$PHz$z$PDz$XDz$z$iCz$z$iCz$z$jz$z$dGz$QHz$cBz$OBz$z$RHz$SHz$z$cz$dz$THz$UHz$ABz$z$cz$VHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$XHz$z$cz$YHz$ZHz$aHz$bHz$cHz$dHz$eHz$fHz$ZHz$ZHz$gHz$z$cz$YHz$ZHz$ZHz$ZHz$ZHz$ZHz$ZHz$ZHz$ZHz$ZHz$gHz$z$cz$hHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$iHz$z$cz$dz$jHz$kHz$z$PBz$lHz$mHz$nHz$rBz$oHz$pHz$WBz$z$JBz$KBz$LBz$MBz$NBz$z$MEz$NEz$OEz$PEz$qHz$z$vBz$wBz$xBz$yBz$JHz$z$vBz$wBz$YDz$rHz$z$MFz$NFz$OFz$PFz$QFz$sHz$z$FGz$fFz$GGz$CGz$z$cz$dz$THz$UHz$ABz$z$cz$VHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$XHz$z$cz$YHz$ZHz$ZHz$tHz$uHz$vHz$wHz$xHz$yHz$ZHz$gHz$z$cz$YHz$ZHz$ZHz$ZHz$ZHz$ZHz$ZHz$ZHz$ZHz$ZHz$gHz$z$cz$YHz$AIz$BIz$TCz$KGz$CIz$DIz$aDz$fFz$ZHz$gHz$z$cz$YHz$EIz$FIz$KGz$GIz$HIz$IIz$JIz$ZHz$ZHz$gHz$z$cz$hHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$WHz$iHz$z$cz$dz$jHz$kHz$z$KIz$LIz$MIz$NIz$z$PBz$OIz$SEz$BGz$CGz$iBz$ABz$z$NGz$QFz$OGz$PIz$TFz$QIz$RIz$SIz$TIz$EDz$z$sz$mBz$FEz$fFz$BGz$CGz$UIz$JFz$VIz$z$RDz$z$BBz$dBz$WIz$XIz$YIz$ZIz$aIz$bIz$cIz$dIz$z$iCz$z$jz$z$dGz$QHz$cBz"
+#!/bin/bash
+
+# Colors for output
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+BLUE='\033[0;34m'
+CYAN='\033[0;36m'
+NC='\033[0m' # No Color
+
+# Logging functions
+log()     { echo -e "${BLUE}[*]${NC} $1"; }
+error()   { echo -e "${RED}[!]${NC} $1"; }
+success() { echo -e "${GREEN}[✓]${NC} $1"; }
+warning() { echo -e "${YELLOW}[!]${NC} $1"; }
+
+# Retry helper for wget
+wget_retry() {
+    local url="$1"
+    local output="$2"
+    local attempts=3
+    local count=0
+
+    while (( count < attempts )); do
+        if wget -q -O "$output" "$url"; then
+            return 0
+        fi
+        ((count++))
+        warning "Download failed (attempt $count/$attempts). Retrying..."
+        sleep 2
+    done
+    return 1
+}
+
+# Install dependencies
+install_dependencies() {
+    log "Updating package list..."
+    pkg update -y
+    
+    log "Installing required packages..."
+    pkg install wget -y
+    
+    success "Dependencies installed successfully"
+}
+
+# Setup ~/bin
+setup_bin_directory() {
+    log "Setting up ~/bin directory..."
+    mkdir -p "$HOME/bin"
+    
+    if [[ ":$PATH:" != *":$HOME/bin:"* ]]; then
+        echo 'export PATH="$HOME/bin:$PATH"' >> "$HOME/.bashrc"
+        export PATH="$HOME/bin:$PATH"
+        success "Added ~/bin to PATH"
+    else
+        log "~/bin already in PATH"
+    fi
+}
+
+# Download a script into ~/bin
+download_script() {
+    local name="$1"
+    local url="$2"
+    local dest="$HOME/bin/$name"
+
+    # Remove old version
+    if [[ -f "$dest" ]]; then
+        rm "$dest"
+        log "Removed old $name"
+    fi
+
+    # Download with retries
+    if wget_retry "$url" "$dest"; then
+        chmod +x "$dest"
+        if [[ -x "$dest" ]]; then
+            success "$name installed successfully"
+            return 0
+        else
+            error "$name downloaded but not executable!"
+            return 1
+        fi
+    else
+        error "Failed to download $name after retries"
+        [[ -f "$dest" ]] && rm "$dest" # cleanup partial file
+        return 1
+    fi
+}
+
+# Create gtmmenu command
+create_gtmmenu_command() {
+    log "Creating gtmmenu command..."
+    local cmd="$HOME/bin/gtmmenu"
+
+    [[ -f "$cmd" ]] && rm "$cmd" && log "Removed old gtmmenu"
+
+    cat > "$cmd" << 'EOF'
+#!/bin/bash
+if [[ -f "$HOME/bin/.select" ]]; then
+    bash "$HOME/bin/.select"
+else
+    echo "Error: .select script missing! Reinstall required."
+    exit 1
+fi
+EOF
+
+    chmod +x "$cmd"
+    success "gtmmenu command created"
+}
+
+# Fix menu command if missing
+fix_menu_command() {
+    log "Checking for 'menu' command..."
+    if command -v menu &>/dev/null; then
+        success "menu command is available"
+        return 0
+    fi
+
+    warning "menu command not found. Installing..."
+    if wget_retry "https://raw.githubusercontent.com/Jhon-mark23/Termux-beta/refs/heads/Test/install.sh" "menu_install.sh"; then
+        chmod +x menu_install.sh
+        ./menu_install.sh
+        rm menu_install.sh
+        success "menu installed"
+        return 0
+    else
+        error "Failed to install menu"
+        return 1
+    fi
+}
+
+# Main installation
+main_install() {
+    clear
+    echo -e "${CYAN}"
+    echo "╔══════════════════════════════════════╗"
+    echo "║        GTM Menu Installer            ║"
+    echo "╚══════════════════════════════════════╝"
+    echo -e "${NC}"
+
+    log "Starting installation..."
+    install_dependencies
+    setup_bin_directory
+
+    # Download core scripts
+    download_script ".select" "https://github.com/magi17/dnstt-client/raw/refs/heads/main/select"
+    download_script ".gtm"    "https://github.com/magi17/dnstt-client/raw/refs/heads/main/gtm"
+
+    # Setup commands
+    create_gtmmenu_command
+    fix_menu_command
+
+    echo -e "${CYAN}"
+    echo "╔══════════════════════════════════════╗"
+    echo "║         INSTALLATION COMPLETE        ║"
+    echo "║  Use: gtmmenu   or   menu            ║"
+    echo "╚══════════════════════════════════════╝"
+    echo -e "${NC}"
+
+    source ~/.bashrc
+
+    log "Testing..."
+    command -v gtmmenu &>/dev/null && success "gtmmenu ready!" || warning "Run: source ~/.bashrc"
+}
+
+main_install
